lr_schedule: 0.0003
buffer_size: 3000000
learning_starts: 100000
batch_size: 256
tau: 0.02
gamma: 0.95
train_freq: 4
gradient_steps: 4
target_update_interval: 1
total_timesteps: 1000000

actor_net:
- 512
- 512
- 256

critic_net:
- 512
- 512
- 256